name: Docker Togh CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: Build Npm Docker image

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: npm
        run: npm install

      # build and test the apps
      - name: build
        run: npm run build

      - name: Build Frontend Docker image
        working-directory: npm
        run: docker build . --file Dockerfile --tag  pierreyvesmonnet/frontendtogh:1.0.0
